---
- Kalavari:
    Description: 'Kalavari is the royal capital, the home of the Sun King and
      surrounding court. Much of the planet is given over to the sprawling city
      which shares its name, a gleaming art-deco megalopolis home to several
      billion. Kalavari has countless public holidays and a very popular arena
      in which gladiatorial games are held, all serving to distract the public
      from the general drudgery and oppression of life in the Rājya.'
    Notable people:
      - 'The royal court is the centre of wealthy social life, with
      the big names being the members of the four clans Valentine, Wolfe, Oberoi
      and Gulzar. The clans are sprawling, complicated affairs with countless
      minor subclans sprouting from each house – Lt. Col. Silence, who you met
      in the first session, is from a minor branch of the Valentine clan.  The
      monarch appoints an heir from one of the major clans, and a new monarch
      renounces all ties to their clan upon taking the throne. (The current Sun
      King was once Rhajiv Ghatak Oberoi, but clan Oberoi gets no special
      treatment these days.)'
    Noteworthy places:
      - Akhāṛā: 'Where the most spectacular of games are held, and the of
        fights. Tickets are kept deliberately cheap, so that the common folk can
        attend. The most popular fighter is the Durandal, a masked swordsman of
        great skill.'
      - The Drowned Heron: 'A slummy little bar tucked deep in the undercity.
        Home to some rather terrifying drinks specials and a curiously stocked
        holo jukebox, it’s also reputed to be a meeting place for the
        anti-royalists movement.'
