---
- Kalavari:
    Description: 'Kalavari is the royal capital, the home of the Sun King and
      surrounding court. Much of the planet is given over to the sprawling city
      which shares its name, a gleaming art-deco megalopolis home to several
      billion. Kalavari has countless public holidays and a very popular arena
      in which gladiatorial games are held, all serving to distract the public
      from the general drudgery and oppression of life in the Rājya.'
    Notable people:
      - 'The royal court is the centre of wealthy social life, with
      the big names being the members of the four clans Valentine, Wolfe, Oberoi
      and Gulzar. The clans are sprawling, complicated affairs with countless
      minor subclans sprouting from each house – Lt. Col. Silence, who you met
      in the first session, is from a minor branch of the Valentine clan.  The
      monarch appoints an heir from one of the major clans, and a new monarch
      renounces all ties to their clan upon taking the throne. (The current Sun
      King was once Rhajiv Ghatak Oberoi, but clan Oberoi gets no special
      treatment these days.)'
    Noteworthy places:
      - Akhāṛā: 'Where the most spectacular of games are held, and the of
        fights. Tickets are kept deliberately cheap, so that the common folk can
        attend. The most popular fighter is the Durandal, a masked swordsman of
        great skill.'
      - The Drowned Heron: 'A slummy little bar tucked deep in the undercity.
        Home to some rather terrifying drinks specials and a curiously stocked
        holo jukebox, it’s also reputed to be a meeting place for the
        anti-royalists movement.'
- Corilia:
    Description: 'A large planet on the edge of the empire with three moons,
      Primus, Secundus and Tertius, of which Primus and Tertius support life.
      The planet itself if covered in a single, all consuming ruin of a past
      civilisation. Access to the planet is forbidden, although enforcement is
      patchy at best and a thriving trade of artifacts and trinkets scavenged
      from the surface exists on Corilia Primus and Corilia Tertius.'
    Noteworthy places:
      - Corilia Primus: 'Sparsely populated and has a climate well suited to a
      fruit the locals produce alcohol from. The drink, similar to gin, is the
      system''s primary export.'
      - Corilia Secundus: 'Home to an Imperial Naval base until approx. fifty
      years ago. The local ruling class fell out of favour and naval assets were
      moved to more politically expedient climes. A group of smugglers now
      occupy the base.'
      - Corilia Tertius: 'Home to around a billion people, largely supporting
      Corilia University and the archeological teams they send to the planet''s
      surface. There have been troubles recently between archeologists and
      groups of Senders who have declared themselves the "inheritors of Corilia"
      and settled on the planet.'
- Lupa:
    Description: 'The ancestral home of the Tē, this desert world is only
      sparsely populated, with most of that population in the capital on the
      edge of the largest oasis on the planet. The Tē are a peaceful and
      co-operative race, and after their conquer by the Sun King, the lack of
      resources and low chance of uprising meant the planet was mostly left to
      its own devices.'
    Notable people:
      - 'Lupa is a word with few travellers across it, most citizens staying in
      the town they were born in. However, there is a rumour of a traveller who
      brings water to the thirsty and lends aid to the needy - Inaama. This
      person, if they exist, is also said to control all smuggling on the planet.'
      - 'Goverment of the cities is done consistently in the same, traditional
      manner. Every 50 years a leader, or Puno, is selected at random from the
      working population, to lead and direct the civilisation. This role has no
      glamour to it, but is considered an honourable duty.'
    Noteworthy places:
      - Basa: 'The main city of Lupa. Upwards of a million Tē live here, making
        this a roiling metropolis in modern terms. As with all cities on the
        planet it is next to an oasis, with convenient trade routes provided by
        the nearby canyons. It is rumoured that underneath Basa is a great
        treasure, but ground scans have indicated nothing more than aquifers.
        Given the planet''s arid nature, these are believed to be the source of
        the myth.'
- Paradise:
    Description: 'A resort planet, a luxury destination for wealthy and
      influential Senders. Its shining beaches, temperate weather and exotic
      jungles required only mild terraforming to draw customers from across the
      galaxy to relax and enjoy themselves. Paradise''s luxurious resorts are
      staffed almost entirely by Omiri, a diminutive species of six-limbed
      primates who are in fashion as servants. Large portions of the jungle have
      been cleared and replanted to make them habitable for the Omiri, who
      prefer a more arid climate.'
    Notable people:
      - 'The sentient natives of Paradise, the Ss''ur, are
      reptilian, and call the planet Ahh''ssst. They have never been in fashion
      as servants, and their hunting culture is increasingly unviable as more
      and more of the planet''s ecosystem is repurposed for Sender leisure.'
- Khō Gayā:
    Description: 'A rebel planet which has managed to resist the Rajya''s
      attempts at control so far. Populated by renegade espers, criminals,
      bounty hunters, deserters, and revolutionaries, Khō Gayā is a harsh place
      with bitterly cold and miserable weather. The espers maintain a
      telekenetic shield around the planet to protect it from Royal attack,
      though rumour has it that the Sun King''s forces are working on ways to
      circumvent this.'
    Notable people:
      - 'Lazarus D''ark, Professional Rebel. Once the official Enemy of the
      Rajya, until the rogue AIs became a greater threat. Has led countless
      rebellions, and though he''s always lost eventually he won enough to
      become something of a legend. Betrayed, arrested and tortured by the
      secret police, fled to Khō Gayā after escaping.'
      - 'Sapphire Voyage. A formidable bounty hunter with a famous bloodlust.
      Frequent partner in crime of D''ark.'
- Ānsū:
    Description: 'A galactic Leprosarium, the landmasses of which are covered
      with red plants. A constant rainfall covers most of the planet with
      complex underground caverns holding most of the water before it evaporates
      back into the atmosphere. Random data from the archive: Rumours persist
      of something called the "Red Brain", though specifics of who or what it is
      are scarce.'
    Noteworthy places:
      - Merrowmont: 'The largest colony on the planet. The sufferers are tended
        to by an enigmatic sect of monks who turn away almost all visitors to
        the planet.'
- Hakeldama:
    Description: 'A pleasure planet, a planet-wide theme park. Hakeldama used
      robots to recreate a popular range of children''s entertainment, allowing
      their wealthy clientele to live among the characters of their youths.
      Quarantined 13 years ago following an unknown incident, possibly involving
      the rogue AIs.'
    Notable people:
      - 'A Royal Navy Rear Admiral, Shannon Harker, crashed her dreadnought on
      Hakeldama several years ago. Harker and her crew have not been heard from
      since and are believed dead.'
- Udyōga IV:
    Description: 'A techno-industrial world, one of the key manufacturing
      centres of the Rajya. The surface has entirely vanished beneath
      interlocking factories. Clan Gulzar has responsibility for the world and
      its output.'
    Noteworthy places:
      - Facility 17: 'A secure R&D site used for the development of cutting edge
        starship weapons. It is possibly one of the most heavily guarded places
        outside of the Sun King''s palace.'
